package io.miragon.blueprint.adapter.outbound.engine;

import io.miragon.blueprint.application.port.outbound.LeasingProcess;
import io.miragon.blueprint.domain.bike.BikeId;
import io.miragon.blueprint.domain.leasing.ApplicationId;
import io.miragon.blueprint.domain.leasing.LeasingApplication;
import io.miragon.blueprint.process.BikeLeasingProcessProcessApi.Elements;
import io.miragon.blueprint.process.BikeLeasingProcessProcessApi.Messages;
import io.miragon.blueprint.process.BikeLeasingProcessProcessApi.Variables;
import org.cibseven.rest.client.api.MessageApi;
import org.cibseven.rest.client.api.TaskApi;
import org.cibseven.rest.client.model.CompleteTaskDto;
import org.cibseven.rest.client.model.CorrelationMessageDto;
import org.cibseven.rest.client.model.TaskWithAttachmentAndCommentDto;
import org.cibseven.rest.client.model.VariableValueDto;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Drives the <i>remote</i> CIB seven engine over its REST API ({@code /engine-rest}): starts the process via its
 * message start event, correlates the messages that release the wait states, and completes the
 * alternative-clarification user task from the outside. The service-tasks are handled separately via
 * the external-task client.
 *
 * <p>The REST calls go through the <b>autogenerated</b> CIB seven client ({@link MessageApi}, {@link TaskApi}) from
 * {@code common-cibseven-client}, so URIs, request/response shapes and the typed-variable payload are typed
 * rather than hand-built. As in the embedded blueprint, the {@link ApplicationId} is used as the <b>process
 * business key</b>, so messages and user-task lookups correlate to the right instance by business key.
 * Variable and element names come from the typed process API this service generates from its own
 * {@code bike-leasing.bpmn}.
 */
@Component
public class RemoteLeasingProcessAdapter implements LeasingProcess {

    private static final Logger log = LoggerFactory.getLogger(RemoteLeasingProcessAdapter.class);

    private final MessageApi messageApi;
    private final TaskApi taskApi;

    public RemoteLeasingProcessAdapter(MessageApi messageApi, TaskApi taskApi) {
        this.messageApi = messageApi;
        this.taskApi = taskApi;
    }

    @Override
    public void submitRequest(LeasingApplication application) {
        Map<String, VariableValueDto> processVariables = new LinkedHashMap<>();
        processVariables.put(
                Variables.StartEventLeasingRequestReceived.APPLICATION_ID.getValue(),
                typedVar(application.id().value().toString()));
        processVariables.put(
                Variables.StartEventLeasingRequestReceived.BIKE_ID.getValue(),
                typedVar(application.bikeId().value()));
        processVariables.put(
                Variables.StartEventLeasingRequestReceived.MONTHLY_NET_INCOME.getValue(),
                typedVar(application.monthlyNetIncome()));
        processVariables.put(
                Variables.StartEventLeasingRequestReceived.AGE.getValue(),
                typedVar(application.age()));
        messageApi.deliverMessageWithHttpInfo(
                new CorrelationMessageDto()
                        .messageName(Messages.MIRAVELO_LEASING_REQUEST_RECEIVED.getValue())
                        .businessKey(application.id().value().toString())
                        .processVariables(processVariables));
        log.info("Started remote leasing process for application {}", application.id().value());
    }

    @Override
    public void correlateContractSigned(ApplicationId id) {
        correlateByBusinessKey(Messages.MIRAVELO_CONTRACT_SIGNED.getValue(), id);
    }

    @Override
    public void correlateHandoverReported(ApplicationId id) {
        correlateByBusinessKey(Messages.MIRAVELO_HANDOVER_REPORTED.getValue(), id);
    }

    @Override
    public void correlateApplicationWithdrawn(ApplicationId id) {
        correlateByBusinessKey(Messages.MIRAVELO_APPLICATION_WITHDRAWN.getValue(), id);
    }

    /**
     * Completes the {@code Clarify alternative with customer} user task via the engine's REST API — the same
     * task a human could complete through its deployed Camunda Form in the Tasklist.
     */
    @Override
    public void completeAlternativeClarification(
            ApplicationId id,
            boolean alternativeFound,
            @Nullable BikeId bikeId
    ) {
        String taskId = findTaskId(id, Elements.USER_TASK_CLARIFY_ALTERNATIVE.getValue());
        Map<String, VariableValueDto> variables = new LinkedHashMap<>();
        variables.put(Variables.UserTaskClarifyAlternative.ALTERNATIVE_FOUND.getValue(), typedVar(alternativeFound));
        // The re-order reads the same start-injected bike variable, so reuse its name.
        if (bikeId != null) {
            variables.put(Variables.StartEventLeasingRequestReceived.BIKE_ID.getValue(), typedVar(bikeId.value()));
        }
        taskApi.completeWithHttpInfo(taskId, new CompleteTaskDto().variables(variables));
        log.info("Completed clarify-alternative task ({}) for application {}", taskId, id.value());
    }

    private void correlateByBusinessKey(String messageName, ApplicationId id) {
        messageApi.deliverMessageWithHttpInfo(
                new CorrelationMessageDto().messageName(messageName).businessKey(id.value().toString()));
        log.info("Correlated '{}' to application {}", messageName, id.value());
    }

    private String findTaskId(ApplicationId id, String taskDefinitionKey) {
        List<TaskWithAttachmentAndCommentDto> tasks = taskApi.getTasks(
                new TaskApi.GetTasksRequest()
                        .processInstanceBusinessKey(id.value().toString())
                        .taskDefinitionKey(taskDefinitionKey));
        return tasks.stream()
                .findFirst()
                .map(TaskWithAttachmentAndCommentDto::getId)
                .orElseThrow(() -> new IllegalStateException(
                        "No active task '" + taskDefinitionKey + "' found for application " + id.value()));
    }

    /** Wraps a Java value as the engine's typed process-variable payload ({@code { value, type }}). */
    private VariableValueDto typedVar(@Nullable Object value) {
        String type = switch (value) {
            case null -> "Null";
            case String s -> "String";
            case Boolean b -> "Boolean";
            case Integer i -> "Integer";
            case Long l -> "Long";
            case Double d -> "Double";
            default -> throw new IllegalStateException("Unsupported process-variable type: " + value.getClass());
        };
        return new VariableValueDto().value(value).type(type);
    }
}
