package io.miragon.blueprint;

import org.cibseven.rest.client.ApiClient;
import org.cibseven.rest.client.api.MessageApi;
import org.cibseven.rest.client.api.ProcessInstanceApi;
import org.cibseven.rest.client.api.TaskApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestClient;

import java.time.Clock;

/**
 * The remote worker + business logic. It hosts the domain, use cases and adapters, subscribes to the
 * engine's external service-tasks over the external-task client, and drives the process (start, user
 * tasks, messages) over the engine's REST API. The CIB seven engine itself runs in {@code engine-service}.
 */
@SpringBootApplication
public class ExampleServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(ExampleServiceApplication.class, args);
    }

    /** Single source of "now" for the app, so time-dependent logic can be pinned in tests. */
    @Bean
    public Clock clock() {
        return Clock.systemDefaultZone();
    }

    /**
     * {@link RestClient} pointed at the remote CIB seven engine's REST API. It backs the autogenerated CIB
     * seven client APIs below and the multipart deployment adapter, so the base URL is configured once.
     */
    @Bean
    public RestClient engineRestClient(
            @Value("${bike-leasing.engine-rest-base-url}") String baseUrl
    ) {
        return RestClient.builder()
                .baseUrl(baseUrl)
                .build();
    }

    /**
     * Shared {@link ApiClient} of the autogenerated CIB seven client, on top of {@link #engineRestClient}. The
     * generated client builds absolute URLs from its own base path, so it is set to the same engine base URL.
     */
    @Bean
    public ApiClient engineApiClient(
            RestClient engineRestClient,
            @Value("${bike-leasing.engine-rest-base-url}") String baseUrl
    ) {
        return new ApiClient(engineRestClient).setBasePath(baseUrl);
    }

    /** Autogenerated CIB seven {@code /message} client — correlates messages that release the wait states. */
    @Bean
    public MessageApi messageApi(ApiClient engineApiClient) {
        return new MessageApi(engineApiClient);
    }

    /** Autogenerated CIB seven {@code /task} client — queries and completes user tasks. */
    @Bean
    public TaskApi taskApi(ApiClient engineApiClient) {
        return new TaskApi(engineApiClient);
    }

    /** Autogenerated CIB seven {@code /process-instance} client — resolves business keys for the task inbox. */
    @Bean
    public ProcessInstanceApi processInstanceApi(ApiClient engineApiClient) {
        return new ProcessInstanceApi(engineApiClient);
    }
}
