package io.miragon.blueprint.adapter.outbound.engine;

import static io.miragon.blueprint.domain.leasing.TestObjectBuilder.testLeasingApplication;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;
import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.jsonPath;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

import io.miragon.blueprint.domain.bike.BikeId;
import io.miragon.blueprint.domain.leasing.LeasingApplication;
import org.cibseven.rest.client.ApiClient;
import org.cibseven.rest.client.api.MessageApi;
import org.cibseven.rest.client.api.TaskApi;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;
import org.springframework.web.client.RestClient;

/**
 * Verifies the outbound adapter speaks the expected CIB seven REST dialect: the
 * {@link io.miragon.blueprint.domain.leasing.ApplicationId} is used as the business key, the message-start
 * carries typed process variables, and the user task is looked
 * up by business key before being completed. This is also the regression guard proving the
 * autogenerated client emits the same wire format the hand-built one did.
 */
class RemoteLeasingProcessAdapterTest {

    private MockRestServiceServer server;
    private RemoteLeasingProcessAdapter underTest;

    @BeforeEach
    void setUp() {
        RestClient.Builder builder = RestClient.builder().baseUrl("http://engine/engine-rest");
        server = MockRestServiceServer.bindTo(builder).build();
        ApiClient client = new ApiClient(builder.build()).setBasePath("http://engine/engine-rest");
        underTest = new RemoteLeasingProcessAdapter(new MessageApi(client), new TaskApi(client));
    }

    @Test
    @DisplayName("submitRequest starts the process via its message start event with typed variables")
    void submitRequestStartsTheProcessViaItsMessageStartEventWithTypedVariables() {

        // given: a valid application and an engine that accepts the start message
        LeasingApplication application = testLeasingApplication();
        server.expect(requestTo("http://engine/engine-rest/message"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.messageName").value("miravelo.leasingRequestReceived"))
                .andExpect(jsonPath("$.businessKey").value(application.id().value().toString()))
                .andExpect(jsonPath("$.processVariables.applicationId.value").value(application.id().value().toString()))
                .andExpect(jsonPath("$.processVariables.bikeId.value").value(application.bikeId().value()))
                .andExpect(jsonPath("$.processVariables.monthlyNetIncome.type").value("Double"))
                .andExpect(jsonPath("$.processVariables.age.type").value("Integer"))
                .andRespond(withSuccess());

        // when: the request is submitted
        underTest.submitRequest(application);

        // then: exactly the expected call was made
        server.verify();
    }

    @Test
    @DisplayName("correlateContractSigned sends the message correlated by business key")
    void correlateContractSignedSendsTheMessageCorrelatedByBusinessKey() {

        // given: an engine that accepts the correlation
        LeasingApplication application = testLeasingApplication();
        server.expect(requestTo("http://engine/engine-rest/message"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.messageName").value("miravelo.contractSigned"))
                .andExpect(jsonPath("$.businessKey").value(application.id().value().toString()))
                .andRespond(withSuccess());

        // when: the contract-signed message is correlated
        underTest.correlateContractSigned(application.id());

        // then: the message was sent
        server.verify();
    }

    @Test
    @DisplayName("completeAlternativeClarification looks up the task by business key and completes it")
    void completeAlternativeClarificationLooksUpTheTaskByBusinessKeyAndCompletesIt() {

        // given: one active clarify-alternative task for the application
        LeasingApplication application = testLeasingApplication();
        server.expect(requestTo(containsString("/task?")))
                .andExpect(method(HttpMethod.GET))
                .andRespond(withSuccess("[{\"id\":\"task-1\"}]", MediaType.APPLICATION_JSON));
        server.expect(requestTo("http://engine/engine-rest/task/task-1/complete"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.variables.alternativeFound.value").value(true))
                .andExpect(jsonPath("$.variables.bikeId.value").value("BIKE-100"))
                .andRespond(withSuccess());

        // when: the alternative is confirmed with a replacement bike
        underTest.completeAlternativeClarification(application.id(), true, new BikeId("BIKE-100"));

        // then: both the lookup and completion happened
        server.verify();
    }

    @Test
    @DisplayName("findTaskId fails when no active task exists")
    void findTaskIdFailsWhenNoActiveTaskExists() {

        // given: the engine reports no active task
        LeasingApplication application = testLeasingApplication();
        server.expect(requestTo(containsString("/task?")))
                .andExpect(method(HttpMethod.GET))
                .andRespond(withSuccess("[]", MediaType.APPLICATION_JSON));

        // when / then: completing the clarification surfaces the missing task
        Throwable error = catchThrowable(() -> underTest.completeAlternativeClarification(application.id(), false, null));
        assertThat(error).isInstanceOf(IllegalStateException.class);
        server.verify();
    }
}
